//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3615
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("PersonalCenterModel", "FK_AccountInfos_Users1", "Users", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PersonalCenter.Entity.Users), "Records", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PersonalCenter.Entity.Records))]

// 原始文件名:
// 生成日期: 12/30/2010 4:44:08 PM
namespace PersonalCenter.Entity
{
    
    /// <summary>
    /// 架构中不存在 PersonalCenterEntities 的注释。
    /// </summary>
    public partial class PersonalCenterEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// 请使用应用程序配置文件的“PersonalCenterEntities”部分中的连接字符串初始化新 PersonalCenterEntities 对象。
        /// </summary>
        public PersonalCenterEntities() : 
                base("name=PersonalCenterEntities", "PersonalCenterEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// 初始化新的 PersonalCenterEntities 对象。
        /// </summary>
        public PersonalCenterEntities(string connectionString) : 
                base(connectionString, "PersonalCenterEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// 初始化新的 PersonalCenterEntities 对象。
        /// </summary>
        public PersonalCenterEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "PersonalCenterEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// 架构中不存在 Users 的注释。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Users> Users
        {
            get
            {
                if ((this._Users == null))
                {
                    this._Users = base.CreateQuery<Users>("[Users]");
                }
                return this._Users;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Users> _Users;
        /// <summary>
        /// 架构中不存在 Records 的注释。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Records> Records
        {
            get
            {
                if ((this._Records == null))
                {
                    this._Records = base.CreateQuery<Records>("[Records]");
                }
                return this._Records;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Records> _Records;
        /// <summary>
        /// 架构中不存在 Users 的注释。
        /// </summary>
        public void AddToUsers(Users users)
        {
            base.AddObject("Users", users);
        }
        /// <summary>
        /// 架构中不存在 Records 的注释。
        /// </summary>
        public void AddToRecords(Records records)
        {
            base.AddObject("Records", records);
        }
    }
    /// <summary>
    /// 架构中不存在 PersonalCenterModel.Users 的注释。
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="PersonalCenterModel", Name="Users")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Users : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 Users 对象。
        /// </summary>
        /// <param name="id">Id 的初始值。</param>
        /// <param name="account">Account 的初始值。</param>
        /// <param name="uname">Uname 的初始值。</param>
        /// <param name="password">Password 的初始值。</param>
        public static Users CreateUsers(int id, string account, string uname, string password)
        {
            Users users = new Users();
            users.Id = id;
            users.Account = account;
            users.Uname = uname;
            users.Password = password;
            return users;
        }
        /// <summary>
        /// 架构中不存在属性 Id 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// 架构中不存在属性 Account 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Account
        {
            get
            {
                return this._Account;
            }
            set
            {
                this.OnAccountChanging(value);
                this.ReportPropertyChanging("Account");
                this._Account = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Account");
                this.OnAccountChanged();
            }
        }
        private string _Account;
        partial void OnAccountChanging(string value);
        partial void OnAccountChanged();
        /// <summary>
        /// 架构中不存在属性 Uname 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Uname
        {
            get
            {
                return this._Uname;
            }
            set
            {
                this.OnUnameChanging(value);
                this.ReportPropertyChanging("Uname");
                this._Uname = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Uname");
                this.OnUnameChanged();
            }
        }
        private string _Uname;
        partial void OnUnameChanging(string value);
        partial void OnUnameChanged();
        /// <summary>
        /// 架构中不存在属性 Password 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this._Password;
            }
            set
            {
                this.OnPasswordChanging(value);
                this.ReportPropertyChanging("Password");
                this._Password = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Password");
                this.OnPasswordChanged();
            }
        }
        private string _Password;
        partial void OnPasswordChanging(string value);
        partial void OnPasswordChanged();
        /// <summary>
        /// 架构中不存在属性 Email 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this.ReportPropertyChanging("Email");
                this._Email = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Email");
                this.OnEmailChanged();
            }
        }
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// 架构中不存在属性 Skin 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Skin
        {
            get
            {
                return this._Skin;
            }
            set
            {
                this.OnSkinChanging(value);
                this.ReportPropertyChanging("Skin");
                this._Skin = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Skin");
                this.OnSkinChanged();
            }
        }
        private string _Skin;
        partial void OnSkinChanging(string value);
        partial void OnSkinChanged();
        /// <summary>
        /// 架构中不存在 Records 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("PersonalCenterModel", "FK_AccountInfos_Users1", "Records")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Records> Records
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Records>("PersonalCenterModel.FK_AccountInfos_Users1", "Records");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Records>("PersonalCenterModel.FK_AccountInfos_Users1", "Records", value);
                }
            }
        }
    }
    /// <summary>
    /// 架构中不存在 PersonalCenterModel.Records 的注释。
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="PersonalCenterModel", Name="Records")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Records : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 Records 对象。
        /// </summary>
        /// <param name="id">Id 的初始值。</param>
        /// <param name="account">Account 的初始值。</param>
        /// <param name="type">Type 的初始值。</param>
        /// <param name="remark">Remark 的初始值。</param>
        /// <param name="createDate">CreateDate 的初始值。</param>
        /// <param name="lastModifyDate">LastModifyDate 的初始值。</param>
        public static Records CreateRecords(int id, string account, string type, string remark, global::System.DateTime createDate, global::System.DateTime lastModifyDate)
        {
            Records records = new Records();
            records.Id = id;
            records.Account = account;
            records.Type = type;
            records.Remark = remark;
            records.CreateDate = createDate;
            records.LastModifyDate = lastModifyDate;
            return records;
        }
        /// <summary>
        /// 架构中不存在属性 Id 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// 架构中不存在属性 Account 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Account
        {
            get
            {
                return this._Account;
            }
            set
            {
                this.OnAccountChanging(value);
                this.ReportPropertyChanging("Account");
                this._Account = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Account");
                this.OnAccountChanged();
            }
        }
        private string _Account;
        partial void OnAccountChanging(string value);
        partial void OnAccountChanged();
        /// <summary>
        /// 架构中不存在属性 Type 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                this.OnTypeChanging(value);
                this.ReportPropertyChanging("Type");
                this._Type = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Type");
                this.OnTypeChanged();
            }
        }
        private string _Type;
        partial void OnTypeChanging(string value);
        partial void OnTypeChanged();
        /// <summary>
        /// 架构中不存在属性 Remark 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark
        {
            get
            {
                return this._Remark;
            }
            set
            {
                this.OnRemarkChanging(value);
                this.ReportPropertyChanging("Remark");
                this._Remark = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Remark");
                this.OnRemarkChanged();
            }
        }
        private string _Remark;
        partial void OnRemarkChanging(string value);
        partial void OnRemarkChanged();
        /// <summary>
        /// 架构中不存在属性 CreateDate 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return this._CreateDate;
            }
            set
            {
                this.OnCreateDateChanging(value);
                this.ReportPropertyChanging("CreateDate");
                this._CreateDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CreateDate");
                this.OnCreateDateChanged();
            }
        }
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();
        /// <summary>
        /// 架构中不存在属性 LastModifyDate 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime LastModifyDate
        {
            get
            {
                return this._LastModifyDate;
            }
            set
            {
                this.OnLastModifyDateChanging(value);
                this.ReportPropertyChanging("LastModifyDate");
                this._LastModifyDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LastModifyDate");
                this.OnLastModifyDateChanged();
            }
        }
        private global::System.DateTime _LastModifyDate;
        partial void OnLastModifyDateChanging(global::System.DateTime value);
        partial void OnLastModifyDateChanged();
        /// <summary>
        /// 架构中不存在 Users 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("PersonalCenterModel", "FK_AccountInfos_Users1", "Users")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Users Users
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Users>("PersonalCenterModel.FK_AccountInfos_Users1", "Users").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Users>("PersonalCenterModel.FK_AccountInfos_Users1", "Users").Value = value;
            }
        }
        /// <summary>
        /// 架构中不存在 Users 的注释。
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Users> UsersReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Users>("PersonalCenterModel.FK_AccountInfos_Users1", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Users>("PersonalCenterModel.FK_AccountInfos_Users1", "Users", value);
                }
            }
        }
    }
}
